name: lidar-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - scikit-image=0.14
  - numpy
  - matplotlib
  - scipy
  - gdal
  - imageio
  - pip:
    - pygdal
    - lidar
    - tifffile
    - requests
    - googledrivedownloader


